# Generated by Django 5.1.7 on 2025-03-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_event_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='background_image',
            new_name='image_file',
        ),
    ]
