# Generated by Django 5.1.7 on 2025-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_background_image_event_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_file',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/images/'),
        ),
    ]
